### ISSUE TITLE
links management, bug after re-parsing

### ISSUE THREAD

**Issue by annemonceaux** [ModelWriter/Source#4]
après avoir lancé un parsing avec une conf donnée (ex. identity)> apparition de lozanges verts à gauche des lignes contenant des suggestions. Si on relance le parsing avec une autre config (par ex ajouter synonyms) => il y a concaténation des deux listes de liens, donc plus de liens que d'occurrences du mot dans la phrase...

**Comment by ylussaud** [comment]
Fixed in commit 0223247b436cf48ae22c3576af0771383b9b3bf0
